<div class="row">
	<div class="col-md-12">
		<h3>O nama</h3>
		<p>
		Turistička agencija World osnovana je 1983. godine u Beogradu - danas je jedan od vodećih turoperatora u Srbiji. Bavimo se organizacijom aranžmana u zemlji i inostranstvu, prodajom avio karata, kao i minibus prevozom putnika. Odličnu poziciju na tržištu obezbedili smo opredelivši se za kvalitet, sigurnost i otvoren odnos sa putnicima prema kojima smo godinama oblikovali svoju ponudu. Kao siguran partner kod svojih saradnika u inostranstvu - garantujemo adekvatan tretman za pravi odmor svojim klijentima. Devedesetih godina bili smo poznati kao agencija sa najkvalitetnijom i najobimnijom ponudom za skijaše, a od 2000-te godine kreiramo prve čarter aranžmane za grčka ostrva Krf, Krit, Rodos. 
		</p>
		<p>
		Sada svojom širokom letnjom ponudom Filip Travel obuhvata najlepše destinacije Mediterana (Grčka ostrva: Krf, Krit, Rodos, Zakintos, Skijatos, Kos; Tursku sa kompletnom antalijskom i egejskom regijom, ostrvo Majorka i oblast Costa Brava u Španiji, ostrva Sicilija i Malta, i egzotične zemlje Egipat i Tunis). Još jedan jak brend predstavljaju naša autentična grupna avio i autobuska putovanja. 
		</p>
		<p>
		Zaljubljenici u različite kulture i najlepše evropske metropole u mogućnosti su da u društvu naših najboljih turističkih vodiča i na dobro isplaniranim turama upoznaju najposećenije metropole (Rim, Pariz, Berlin, Amsterdam, Barselona, Lisabon…). Inspiraciju za nove ture pronalazimo u sugestijama i idejama svojih putnika i svake godine tu su nova putovanja poput: Portugalske ture, Sicilijanske ture, putovanja Baltičke zemlje i Zemlje Beneluksa, Švajcarska i Lihtenštajn… Za sve vas koji želite da putovanja skrojimo prema vašim afinitetima – tu smo da vaše ideje i potrebe pretočimo u realnost koja će vas odvesti do najudaljenijih meridijana širom sveta. Sektor individualnih putovanja agencija World može zadovoljiti i najsofisticiranije zahteve svetskih putnika. U saradnji sa najkredibilnijim hotelskim sistemima: GTA, Hotelbeds, HotelsPro, GoGlobal, Dertur/Meier’s kao i sa svim svetskim avio kompanijama (ponosni smo nosioc licence IATA) – uključujući i low cost kompanije – svojim klijentima omogućavamo najpovoljnije ponude za odabrane destinacije i termine. 
		</p>		
		<p>		
		Među atraktivnim ponudama nalazi se i veliki broj prestižnih wellness & spa hotela u Sloveniji i Mađarskoj (Agencija World najbolji prodavac prethodnih godina: terme Olimia, terme Laško, terme Čatež i Aquaworld Budapest Resort). Pored naših prodajnih mesta (četiri u Beogradu i jedna poslovnica u Novom Sadu) nesebičnu podršku pruža nam izuzetno veliki broj pouzdanih subagenata širom Srbije, Makedonije, BiH i Crne Gore. Počevši od nasmejanih, ljubaznih lica koja vas dočekuju na našim prodajnim mestima u želji da vam obezbede adekvatan odmor, preko onih koji su na destinacijama zaduženi da vaš odmor protekne kako treba – zaključno sa ljudima koji su tu kao podrška u rešavanju eventualnih problema – WORLD TRAVEL na svakom nivou daje maskimum u kvalitetu pružanja uluge. Preko 30 000 zadovoljnih putnika svake godine naša su obaveza da ljubav prema putovanjima pretačemo u najkvalitetnije turističke aranžmane. Turistička agencija World ima poslovnice na: Vračaru, Trgu Nikole Pašića, Novom Beogradu, Vozdovcu i Novom Sadu. Ukoliko imate nekih pitanja, naša služba je tu za vas! Možete nas pozvati radnim danima od 8-20 časova i subotom od 9-15 časova.
		</p>
	</div>	
</div>